# Default settings for C++
compilers=&clang

group.clang.compilers=clang7:clang8:clang9:clang10:clang11
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang.compilerType=clang
group.clang.supportsExecute=true
compiler.clang11.exe=/opt/compiler-explorer/clang-11.0.1/bin/clang++
compiler.clang11.name=clang 11 + Enzyme (main)
compiler.clang11.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-11.so

compiler.clang10.exe=/opt/compiler-explorer/clang-10.0.1/bin/clang++
compiler.clang10.name=clang 10 + Enzyme (main)
compiler.clang10.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-10.so

compiler.clang9.exe=/opt/compiler-explorer/clang-9.0.1/bin/clang++
compiler.clang9.name=clang 9 + Enzyme (main)
compiler.clang9.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-9.so

compiler.clang8.exe=/opt/compiler-explorer/clang-8.0.1/bin/clang++
compiler.clang8.name=clang 8 + Enzyme (main)
compiler.clang8.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-8.so

compiler.clang7.exe=/opt/compiler-explorer/clang-7.1.0/bin/clang++
compiler.clang7.name=clang 7 + Enzyme (main)
compiler.clang7.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-7.so

tools=clangquerydefault:clangquery11:strings:ldd

tools.clangquerydefault.exe=/usr/bin/clang-query
tools.clangquerydefault.name=clang-query (default)
tools.clangquerydefault.type=independent
tools.clangquerydefault.class=clang-query-tool
tools.clangquerydefault.stdinHint=Query commands

tools.clangquery11.exe=/usr/bin/clang-query-11
tools.clangquery11.name=clang-query 11
tools.clangquery11.type=independent
tools.clangquery11.class=clang-query-tool
tools.clangquery11.stdinHint=Query commands

tools.ldd.name=ldd
tools.ldd.exe=/usr/bin/ldd
tools.ldd.type=postcompilation
tools.ldd.class=readelf-tool
tools.ldd.exclude=djggp
tools.ldd.stdinHint=disabled

tools.strings.exe=/usr/bin/strings
tools.strings.name=strings
tools.strings.type=postcompilation
tools.strings.class=strings-tool
tools.strings.exclude=djggp
tools.strings.stdinHint=disabled

defaultCompiler=clang11
postProcess=
demangler=c++filt
demanglerType=cpp
objdumper=objdump
options=
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*|_dl_relocate_static_pie)$
needsMulti=false
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

#################################
#################################
# Installed libs (See c++.amazon.properties for a scheme of libs group)
libs=
