# Default settings for C++
compilers=&clang

group.clang.compilers=clang11
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang.compilerType=clang
compiler.clang11.exe=/usr/bin/clang++-11
compiler.clang11.name=clang 11 + Enzyme (main)
compiler.clang11.options=-Xclang -load -Xclang /opt/compiler-explorer/ClangEnzyme-11.so
compiler.clangdefault.exe=/usr/bin/clang++
compiler.clangdefault.name=clang default

tools=clangquerydefault:clangquery7:clangquery8:clangquery9:clangquery10:strings:ldd

tools.clangquerydefault.exe=/usr/bin/clang-query
tools.clangquerydefault.name=clang-query (default)
tools.clangquerydefault.type=independent
tools.clangquerydefault.class=clang-query-tool
tools.clangquerydefault.stdinHint=Query commands

tools.clangquery11.exe=/usr/bin/clang-query-11
tools.clangquery11.name=clang-query 11
tools.clangquery11.type=independent
tools.clangquery11.class=clang-query-tool
tools.clangquery11.stdinHint=Query commands

tools.ldd.name=ldd
tools.ldd.exe=/usr/bin/ldd
tools.ldd.type=postcompilation
tools.ldd.class=readelf-tool
tools.ldd.exclude=djggp
tools.ldd.stdinHint=disabled

tools.strings.exe=/usr/bin/strings
tools.strings.name=strings
tools.strings.type=postcompilation
tools.strings.class=strings-tool
tools.strings.exclude=djggp
tools.strings.stdinHint=disabled

defaultCompiler=clang11
postProcess=
demangler=c++filt
demanglerType=cpp
objdumper=objdump
#androidNdk=/opt/google/android-ndk-r9c
options=
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*|_dl_relocate_static_pie)$
needsMulti=false
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

#################################
#################################
# Installed libs (See c++.amazon.properties for a scheme of libs group)
libs=
