# Default settings for C
compilers=&clang
defaultCompiler=clang
demangler=c++filt
objdumper=objdump
postProcess=
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*)$
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

group.clang.compilers=cclang11
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
compiler.cclang11.exe=/usr/bin/clang-11
compiler.cclang11.name=clang 11 + Enzyme (main)
compiler.cclangdefault.exe=/usr/bin/clang
compiler.cclangdefault.name=clang default
compiler.cclangccdefault.exe=/usr/bin/clangcc
compiler.cclangccdefault.name=clang default
compiler.clang11.options=-Xclang -load -Xclang /opt/compiler-explorer/ClangEnzyme-11.so

