# Default settings for C
compilers=&clang
defaultCompiler=cclang11
demangler=c++filt
objdumper=objdump
postProcess=
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*)$
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

group.clang.compilers=cclang11:cclang10:cclang9:cclang8:cclang7
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang.supportsExecute=true

compiler.cclang11.exe=/opt/compiler-explorer/clang-11.0.1/bin/clang
compiler.cclang11.name=clang 11 + Enzyme (main)
compiler.clang11.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-11.so

compiler.cclang10.exe=/opt/compiler-explorer/clang-10.0.1/bin/clang
compiler.cclang10.name=clang 10 + Enzyme (main)
compiler.clang10.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-10.so

compiler.cclang9.exe=/opt/compiler-explorer/clang-9.0.1/bin/clang
compiler.cclang9.name=clang 9 + Enzyme (main)
compiler.clang9.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-9.so

compiler.cclang8.exe=/opt/compiler-explorer/clang-8.0.1/bin/clang
compiler.cclang8.name=clang 8 + Enzyme (main)
compiler.clang8.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-8.so

compiler.cclang7.exe=/opt/compiler-explorer/clang-7.1.0/bin/clang
compiler.cclang7.name=clang 7 + Enzyme (main)
compiler.clang7.options=-Xclang -load -Xclang /opt/compiler-explorer/main/ClangEnzyme-7.so


