binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|(_GLOBAL__sub_I_|\.plt).*|.*@plt(-0x[0-9a-f]+)?)$
objdumper=objdump
demangler=c++filt

compilers=irclang:llc:&opt
defaultCompiler=irclang

compiler.irclang.intelAsm=-masm=intel
compiler.irclang.supportsExecute=false
compiler.irclang.groupName=Clang x86-64
compiler.irclang.options=-x ir
compiler.irclang.exe=/usr/bin/clang++
compiler.irclang.name=clang 3.9.1

compiler.llc.compilerType=llc
compiler.llc.supportsExecute=false
compiler.llc.intelAsm=-masm=intel
compiler.llc.groupName=LLVM Static Compiler
compiler.llc.versionRe=LLVM version .*
compiler.llc.exe=/usr/bin/llc
compiler.llc.name=llc

group.opt.compilers=opt7:opt8:opt9:opt10:opt11
group.opt.compilerType=opt
group.opt.supportsBinary=false
group.opt.supportsExecute=true
group.opt.groupName=LLVM optimizer
group.opt.baseName=opt

compiler.opt11.exe=/opt/compiler-explorer/clang-11.0.1/bin/opt
compiler.opt11.name=opt 11 + Enzyme (main)
compiler.opt11.options=-load=/opt/compiler-explorer/main/LLVMEnzyme-11.so -enzyme

compiler.opt10.exe=/opt/compiler-explorer/clang-10.0.1/bin/opt
compiler.opt10.name=opt 10 + Enzyme (main)
compiler.opt10.options=-load=/opt/compiler-explorer/main/LLVMEnzyme-10.so -enzyme

compiler.opt9.exe=/opt/compiler-explorer/clang-9.0.1/bin/opt
compiler.opt9.name=opt 9 + Enzyme (main)
compiler.opt9.options=-load=/opt/compiler-explorer/main/LLVMEnzyme-9.so -enzyme

compiler.opt8.exe=/opt/compiler-explorer/clang-8.0.1/bin/opt
compiler.opt8.name=opt 8 + Enzyme (main)
compiler.opt8.options=-load=/opt/compiler-explorer/main/LLVMEnzyme-8.so -enzyme

compiler.opt7.exe=/opt/compiler-explorer/clang-7.1.0/bin/opt
compiler.opt7.name=opt 7 + Enzyme (main)
compiler.opt7.options=-load=/opt/compiler-explorer/main/LLVMEnzyme-7.so -enzyme
